<?php

/**
 * @file
 * User Interace for LiftIgniter.
 */

/**
 * Implements hook_entity_type_build().
 */
function liftigniter_ui_entity_type_build(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['widget']
    ->setFormClass('edit', 'Drupal\liftigniter_ui\Form\WidgetForm')
    ->setFormClass('add', 'Drupal\liftigniter_ui\Form\WidgetForm')
    ->setFormClass('delete', 'Drupal\liftigniter_ui\Form\WidgetDeleteForm')
    ->setListBuilderClass('Drupal\liftigniter_ui\WidgetListBuilder')
    ->setLinkTemplate('edit-form', '/admin/config/services/liftigniter/{widget}/edit')
    ->setLinkTemplate('delete-form', '/admin/config/services/liftigniter/{widget}/delete');
  $entity_types['template']
    ->setFormClass('edit', 'Drupal\liftigniter_ui\Form\TemplateForm')
    ->setFormClass('add', 'Drupal\liftigniter_ui\Form\TemplateForm')
    ->setFormClass('delete', 'Drupal\liftigniter_ui\Form\TemplateDeleteForm')
    ->setListBuilderClass('Drupal\liftigniter_ui\TemplateListBuilder')
    ->setLinkTemplate('edit-form', '/admin/config/services/liftigniter/template/{template}/edit')
    ->setLinkTemplate('delete-form', '/admin/config/services/liftigniter/template/{template}/delete');
  if (\Drupal::moduleHandler()->moduleExists('liftigniter_inventory')) {
    $entity_types['inventory_mapping']
      ->setFormClass('edit', 'Drupal\liftigniter_ui\Form\InventoryMappingForm')
      ->setFormClass('add', 'Drupal\liftigniter_ui\Form\InventoryMappingForm')
      ->setFormClass('delete', 'Drupal\liftigniter_ui\Form\InventoryMappingDeleteForm')
      ->setListBuilderClass('Drupal\liftigniter_ui\InventoryMappingListBuilder')
      ->setLinkTemplate('edit-form', '/admin/config/services/liftigniter/inventory-mapping/{inventory_mapping}/edit')
      ->setLinkTemplate('delete-form', '/admin/config/services/liftigniter/inventory-mapping/{inventory_mapping}/delete');
  }
}
